networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - mynetwork

  db:
    image: postgres
    container_name: mypostgres
    hostname: mypostgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork