"""add game

Revision ID: 41de8999fd2c
Revises: 0a6ccb5e5153
Create Date: 2024-11-17 22:54:06.884487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41de8999fd2c'
down_revision: Union[str, None] = '0a6ccb5e5153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FINISHED', 'CANCELED', name='gamesstatusenum'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_master_id'), 'games', ['master_id'], unique=False)
    op.create_index(op.f('ix_games_theme_id'), 'games', ['theme_id'], unique=False)
    op.create_table('user_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('GREEN', 'YELLOW', 'RED', name='userlevelenum'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_states')
    op.drop_index(op.f('ix_games_theme_id'), table_name='games')
    op.drop_index(op.f('ix_games_master_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
