"""seed quiz

Revision ID: fd95fdb8887e
Revises: 41de8999fd2c
Create Date: 2024-11-17 22:54:23.469295

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import create_engine, insert
from sqlalchemy.orm import sessionmaker
from app.quiz.models import ThemeModel, QuestionModel, AnswerModel
from app.web.enums import QuestionLevelEnum



# revision identifiers, used by Alembic.
revision: str = 'fd95fdb8887e'
down_revision: Union[str, None] = '41de8999fd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


file_path = 'alembic/mock/quiz/data.json'
with open(file_path, 'r', encoding='utf-8') as file:
    themes_data = json.load(file)

engine = create_engine('postgresql+asyncpg://postgres:123@localhost/postgres')
Session = sessionmaker(bind=engine)
session = Session()

def upgrade() -> None:
    to_insert_themes = []
    to_insert_questions = []
    to_insert_answers = []

    for theme_data in themes_data:
        theme_id = len(to_insert_themes) + 1
        theme = {
            "id": theme_id,
            'title': theme_data['title'],
            'description': theme_data['description']
        }
        to_insert_themes.append(theme)

        for question_data in theme_data['questions']:
            question_id = len(to_insert_questions) + 1
            question = {
                "id": question_id,
                'title': question_data['title'],
                'level': QuestionLevelEnum[question_data['level'].upper()],
                'theme_id': theme_id
            }
            to_insert_questions.append(question)

            for answer_data in question_data['answers']:
                answer_id = len(to_insert_answers) + 1
                answer = {
                    "id": answer_id,
                    'title': answer_data['title'],
                    'is_correct': answer_data['is_correct'],
                    'question_id': question_id
                }
                to_insert_answers.append(answer)

    session.execute(
        insert(ThemeModel),
        to_insert_themes
    )
    session.execute(
        insert(QuestionModel),
        to_insert_questions
    )
    session.execute(
        insert(AnswerModel),
        to_insert_answers
    )
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
